---
- hosts: local
  tasks:
    - name: ansible-pull copy file
      copy:
        src: ansible-pull/index.html
        dest: /var/www/html/
        owner: ansible
        group: ansible
	- name:
	  service:
	    name: apache2
		state: restarted